# Generated by Django 4.0.10 on 2023-06-14 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('relays', '0001_initial'), ('relays', '0002_auto_20201023_1321'), ('relays', '0003_accesstokens_appear_offline'), ('relays', '0004_alter_relayconfigurations_source_channel_and_more'), ('relays', '0005_rename_datetime_messages_timestamp_messages_deleted_and_more'), ('relays', '0006_remove_relayconfigurations_token_and_more'), ('relays', '0007_rename_accesstokens_accesstoken_and_more'), ('relays', '0008_server_users'), ('relays', '0009_message_id_alter_message_message'), ('relays', '0010_alter_message_content'), ('relays', '0011_relaysconfig_user_rename_webhook_webhook_url_and_more'), ('relays', '0012_rename_destinationwebhook_webhook_and_more'), ('relays', '0013_event_channel_parent'), ('relays', '0014_alter_channel_parent'), ('relays', '0015_channel_created'), ('relays', '0016_rename_created_channel_created_at_server_created_at'), ('relays', '0017_alter_channel_recipients_alter_channel_server'), ('relays', '0018_rename_status_webhook_relaysconfig_status_webhooks'), ('relays', '0019_alter_relaysconfig_options_and_more'), ('relays', '0020_alter_accesstoken_id_and_more'), ('relays', '0021_alter_server_users'), ('relays', '0022_alter_channel_recipients'), ('relays', '0023_alter_relaysconfig_options_alter_event_name_and_more'), ('relays', '0024_rename_end_time_event_end_and_more'), ('relays', '0025_message_content_extended_alter_message_content'), ('relays', '0026_message_mention_everyone'), ('relays', '0027_remove_message_relays_mess_message_b5db25_idx_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aadiscordbot', '0009_alter_quotemessage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('Discord', 'Discord'), ('Slack', 'Slack'), ('XMPP', 'XMPP')], default='Discord', max_length=10)),
                ('users', models.IntegerField(default=0, verbose_name='Users')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.server')),
                ('channel_type', models.CharField(choices=[('T', 'Thread'), ('TC', 'GuildChannel.TextChannel'), ('FC', 'GuildChannel.ForumChannel'), ('VC', 'GuildChannel.VoiceChannel'), ('CC', 'GuildChannel.ForumChannel'), ('SC', 'GuildChannel.StageChannel'), ('DM', 'PrivateChannel.DMChannel'), ('GM', 'PrivateChannel.GroupChannel')], default='TC', max_length=2)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Relays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servers', models.ManyToManyField(blank=True, to='relays.server')),
                ('appear_offline', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
            },
        ),
        migrations.CreateModel(
            name='DestinationAADiscordBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('CM', 'Channel Message'), ('DM', 'Direct Message')], default='CM', max_length=2)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aadiscordbot.channels')),
            ],
            options={
                'verbose_name': 'Discord Channel Destination',
                'verbose_name_plural': 'Discord Channel Destinations',
            },
        ),
        migrations.CreateModel(
            name='DestinationWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Destination Webhook',
                'verbose_name_plural': 'Destination Webhooks',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message', models.PositiveBigIntegerField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.PositiveBigIntegerField()),
                ('author_nick', models.CharField(blank=True, max_length=50, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.channel')),
                ('deleted', models.BooleanField(default=False)),
                ('edit_count', models.IntegerField(default=1, verbose_name='Edit Count')),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'unique_together': {('message', 'edit_count')},
            },
        ),
        migrations.CreateModel(
            name='RelaysConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Public Market Configuration',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='RelayConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attempt_translation', models.BooleanField(default=False)),
                ('message_mention', models.BooleanField(default=True)),
                ('message_non_mention', models.BooleanField(default=False)),
                ('message_regex', models.CharField(default='.^', max_length=10)),
                ('source_server_all', models.BooleanField(default=False)),
                ('source_channel_all', models.BooleanField(default=False)),
                ('destination_db', models.BooleanField(default=False)),
                ('destination_aadiscordbot', models.ManyToManyField(blank=True, to='relays.destinationaadiscordbot')),
                ('destination_webhook', models.ManyToManyField(blank=True, to='relays.destinationwebhook')),
                ('source_channel', models.ManyToManyField(blank=True, to='relays.channel')),
                ('source_server', models.ManyToManyField(blank=True, to='relays.server')),
            ],
            options={
                'verbose_name': 'Relay Configuration',
                'verbose_name_plural': 'Relay Configurations',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message'], name='relays_mess_message_b5db25_idx'),
        ),
        migrations.AddField(
            model_name='channel',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='relays.user', verbose_name=''),
        ),
        migrations.RenameModel(
            old_name='DestinationWebhook',
            new_name='Webhook',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='webhook',
            new_name='url',
        ),
        migrations.AddField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Only True (currently), if Thread', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_parent', to='relays.channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relays.server'),
        ),
        migrations.AddField(
            model_name='relaysconfig',
            name='status_webhooks',
            field=models.ManyToManyField(to='relays.webhook', verbose_name='Destination Webhook for Status Updates'),
        ),
        migrations.AlterModelOptions(
            name='relaysconfig',
            options={'default_permissions': (), 'verbose_name': 'AA Relays Settings'},
        ),
        migrations.RemoveField(
            model_name='relayconfiguration',
            name='destination_db',
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='destinationaadiscordbot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relayconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relaysconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='users',
            field=models.IntegerField(default=0, verbose_name='Users'),
        ),
        migrations.AlterModelOptions(
            name='relaysconfig',
            options={'default_permissions': (), 'verbose_name': 'AA Relays Settings', 'verbose_name_plural': 'AA Relays Settings'},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ScheduledEvent',
                'verbose_name_plural': 'ScheduledEvents',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='content_extended',
            field=models.TextField(default='', help_text='Additional Content, Embeds, URLs, Attachments etc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='The primary content of a message'),
        ),
        migrations.AddField(
            model_name='message',
            name='mention_everyone',
            field=models.BooleanField(default=False, verbose_name='Message is @everyone'),
            preserve_default=False,
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='relays_mess_message_b5db25_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='mention_everyone',
            field=models.BooleanField(default=False, verbose_name='Message is @everyone'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['server', 'channel_type'], name='relays_chan_server__7a2048_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message', 'channel', 'author'], name='relays_mess_message_849c43_idx'),
        ),
    ]
