# Generated by Django 4.0.10 on 2023-06-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0001_squashed_0027_remove_message_relays_mess_message_b5db25_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='bot',
            field=models.BooleanField(default=False, verbose_name='Is Bot User?'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created Timestamp'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Username'),
        )
    ]
