# Generated by Django 4.0.10 on 2023-06-16 04:20

from django.db import migrations


def populate_user_objects(apps, schema_editor):
    User = apps.get_model('relays', 'User')
    Messages = apps.get_model('relays', 'Message')
    for message in Messages.objects.all():
        try:
            user = User(id=message.author, name=message.author_nick)
            user.save()
        except Exception as e:
            print(e)
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0002_user'),
    ]

    operations = [
        migrations.RunPython(populate_user_objects),
    ]
