# Generated by Django 3.1.4 on 2020-12-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0002_auto_20201023_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstokens',
            name='appear_offline',
            field=models.BooleanField(default=False),
        ),
    ]
