# Generated by Django 4.0.6 on 2022-09-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0003_accesstokens_appear_offline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relayconfigurations',
            name='source_channel',
            field=models.ManyToManyField(blank=True, to='relays.channels'),
        ),
        migrations.AlterField(
            model_name='relayconfigurations',
            name='source_server',
            field=models.ManyToManyField(blank=True, to='relays.servers'),
        ),
    ]
