# Generated by Django 4.0.10 on 2023-06-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0004_alter_relayconfigurations_source_channel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='datetime',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='messages',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='edit_count',
            field=models.IntegerField(default=1, verbose_name='Edit Count'),
        ),
        migrations.AlterUniqueTogether(
            name='messages',
            unique_together={('message', 'edit_count')},
        ),
    ]
