# Generated by Django 4.0.10 on 2023-06-16 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0004_remove_message_relays_mess_message_849c43_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relays.user', verbose_name=''),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message', 'channel', 'author'], name='relays_mess_message_849c43_idx'),
        ),
    ]
