# Generated by Django 4.0.10 on 2023-06-16 04:50

from django.db import migrations


def migrate_author_to_user(apps, schema_editor):
    Messages = apps.get_model('relays', 'Message')
    User = apps.get_model('relays', 'User')
    for message in Messages.objects.all():
        try:
            message.user, created = User.objects.get_or_create(id=message.author)
            message.save()
        except Exception as e:
            print(e)
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0005_message_user_message_relays_mess_message_849c43_idx'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_user),
    ]
