# Generated by Django 4.0.10 on 2023-06-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0007_rename_accesstokens_accesstoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='users',
            field=models.IntegerField(default=0, verbose_name='Users'),
            preserve_default=False,
        ),
    ]
