# Generated by Django 4.0.10 on 2023-06-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0008_server_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
