# Generated by Django 4.0.10 on 2023-06-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0008_remove_message_relays_mess_message_849c43_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
