# Generated by Django 4.0.10 on 2023-06-19 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0009_remove_message_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content_extended',
        ),
        migrations.CreateModel(
            name='MessageEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Message Embed to String')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.message', verbose_name='')),
            ],
            options={
                'verbose_name': 'MessageEmbed',
                'verbose_name_plural': 'MessageEmbeds',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='')),
                ('filename', models.CharField(max_length=50, verbose_name='')),
                ('media_type', models.CharField(max_length=50, verbose_name='')),
                ('url', models.CharField(max_length=50, verbose_name='')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.message', verbose_name='')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
            },
        ),
    ]
