# Generated by Django 4.0.10 on 2023-06-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0010_alter_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelaysConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Public Market Configuration',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('T', 'Thread'), ('TC', 'GuildChannel.TextChannel'), ('FC', 'GuildChannel.ForumChannel'), ('VC', 'GuildChannel.VoiceChannel'), ('CC', 'GuildChannel.ForumChannel'), ('SC', 'GuildChannel.StageChannel'), ('DM', 'PrivateChannel.DMChannel'), ('GM', 'PrivateChannel.GroupChannel')], default='TC', max_length=2),
        ),
        migrations.AddField(
            model_name='channel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message'], name='relays_mess_message_b5db25_idx'),
        ),
        migrations.AddField(
            model_name='channel',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='relays.user', verbose_name=''),
        ),
    ]
