# Generated by Django 4.0.10 on 2023-06-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0011_relaysconfig_user_rename_webhook_webhook_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DestinationWebhook',
            new_name='Webhook',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='webhook',
            new_name='url',
        ),
        migrations.AddField(
            model_name='relaysconfig',
            name='status_webhook',
            field=models.ManyToManyField(to='relays.webhook', verbose_name='Destination Webhook for Status Updates'),
        ),
    ]
