# Generated by Django 4.0.10 on 2023-06-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0012_alter_messageattachment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='filename',
            field=models.CharField(max_length=256, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='url',
            field=models.CharField(max_length=2048, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
