# Generated by Django 4.0.10 on 2023-06-13 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0013_event_channel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Only True (currently), if Thread', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_parent', to='relays.channel'),
        ),
    ]
