# Generated by Django 4.0.10 on 2023-06-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0013_alter_messageattachment_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='channel',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='relays.user', verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='filename',
            field=models.CharField(max_length=256, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Attachment ID'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='media_type',
            field=models.CharField(max_length=50, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='messageembed',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relays.message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='relayconfiguration',
            name='override_colour',
            field=models.CharField(blank=True, choices=[('#3498db', 'Blue'), ('#5865f2', 'blurple'), ('#57f287', 'brand_green'), ('#ed4245', 'brand_red'), ('#206694', 'dark_blue'), ('#c27c0e', 'dark_gold'), ('#607d8b', 'dark_grey'), ('#1f8b4c', 'dark_green'), ('#ad1457', 'dark_magenta'), ('#a84300', 'dark_orange'), ('#71368a', 'dark_purple'), ('#992d22', 'dark_red'), ('#11806a', 'dark_teal'), ('#36393f', 'dark_theme'), ('#546e7a', 'darker_grey'), ('#2b2d31', 'embed_background'), ('#eb459e', 'fuchsia'), ('#f1c40f', 'gold'), ('#2ecc71', 'green'), ('#99aab5', 'greyple'), ('#979c9f', 'light_grey'), ('#95a5a6', 'lighter_grey'), ('#f47fff', 'nitro_pink'), ('#7289da', 'og_blurple'), ('#e67e22', 'orange'), ('#9b59b6', 'purple'), ('#e74c3c', 'red'), ('#1abc9c', 'teal'), ('#fee75c', 'yellow')], max_length=50, verbose_name='Override Colour'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
