# Generated by Django 4.0 on 2023-10-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0014_alter_user_options_alter_channel_recipients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='servers',
            field=models.ManyToManyField(blank=True, to='relays.Server'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='relays.User', verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='relayconfiguration',
            name='destination_aadiscordbot',
            field=models.ManyToManyField(blank=True, to='relays.DestinationAADiscordBot'),
        ),
        migrations.AlterField(
            model_name='relayconfiguration',
            name='source_channels',
            field=models.ManyToManyField(blank=True, to='relays.Channel'),
        ),
        migrations.AlterField(
            model_name='relayconfiguration',
            name='source_servers',
            field=models.ManyToManyField(blank=True, to='relays.Server'),
        ),
        migrations.AlterField(
            model_name='relaysconfig',
            name='status_webhooks',
            field=models.ManyToManyField(to='relays.Webhook', verbose_name='Destination Webhook for Status Updates'),
        ),
    ]
