# Generated by Django 4.0.10 on 2023-06-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0014_alter_channel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
