# Generated by Django 4.0.10 on 2023-06-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0015_channel_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
