# Generated by Django 4.0.10 on 2023-06-13 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0016_rename_created_channel_created_at_server_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, to='relays.user', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relays.server'),
        ),
    ]
