# Generated by Django 4.0.10 on 2023-06-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0018_rename_status_webhook_relaysconfig_status_webhooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relaysconfig',
            options={'default_permissions': (), 'verbose_name': 'AA Relays Settings'},
        ),
        migrations.RemoveField(
            model_name='relayconfiguration',
            name='destination_db',
        ),
    ]
