# Generated by Django 4.0.10 on 2023-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0020_alter_accesstoken_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='users',
            field=models.IntegerField(default=0, verbose_name='Users'),
        ),
    ]
