# Generated by Django 4.0.10 on 2023-06-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0021_alter_server_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='relays.user', verbose_name=''),
        ),
    ]
