# Generated by Django 4.0.10 on 2023-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0022_alter_channel_recipients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relaysconfig',
            options={'default_permissions': (), 'verbose_name': 'AA Relays Settings', 'verbose_name_plural': 'AA Relays Settings'},
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
