# Generated by Django 4.0.10 on 2023-06-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0023_alter_relaysconfig_options_alter_event_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start',
        ),
    ]
