# Generated by Django 4.0.10 on 2023-06-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0025_message_content_extended_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mention_everyone',
            field=models.BooleanField(default=False, verbose_name='Message is @everyone'),
            preserve_default=False,
        ),
    ]
