# Generated by Django 4.0.10 on 2023-06-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0026_message_mention_everyone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='relays_mess_message_b5db25_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='mention_everyone',
            field=models.BooleanField(default=False, verbose_name='Message is @everyone'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['server', 'channel_type'], name='relays_chan_server__7a2048_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message', 'channel', 'author'], name='relays_mess_message_849c43_idx'),
        ),
    ]
